version: "3.9"

services:
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb+srv://vkkhambra786:olsBTIlUOQVT4KLj@cluster0.buill3t.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

 